<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Aswins-Air.adactin.guest" failures="1" tests="1" name="adactin.urbest.testrunner.To_verify_if_client_is_able_to_click_the_forgot_password_button_and_reset_the_credentials" time="5.688" errors="0" timestamp="06 Feb 2020 23:09:53 GMT" skipped="0">
  <testcase classname="adactin.urbest.testrunner.To_verify_if_client_is_able_to_click_the_forgot_password_button_and_reset_the_credentials" name="To_verify_if_client_is_able_to_click_the_forgot_password_button_and_reset_the_credentials" time="5.688">
    <failure message="expected [Forgot Password Link Available and functional] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Forgot Password Link Available and functional] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at adactin.urbest.webpages.Login_Page.validateForgotPWD(Login_Page.java:144)
at adactin.urbest.testrunner.To_verify_if_client_is_able_to_click_the_forgot_password_button_and_reset_the_credentials.To_verify_if_client_is_able_to_click_the_forgot_password_button_and_reset_the_credentials(To_verify_if_client_is_able_to_click_the_forgot_password_button_and_reset_the_credentials.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- To_verify_if_client_is_able_to_click_the_forgot_password_button_and_reset_the_credentials -->
</testsuite> <!-- adactin.urbest.testrunner.To_verify_if_client_is_able_to_click_the_forgot_password_button_and_reset_the_credentials -->
